name: Angular CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.13'

    - name: Install dependencies
      run: npm install

    - name: Lint
      run: npm run lint -- --format json --output-file eslint-report.json || echo "Linting issues found"
      
    - name: Upload ESLint Report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: eslint-report
        path: eslint-report.json

    - name: Build
      run: npm run build -- --configuration production
