name: Prettier PR

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write  # This line gives the workflow write permissions
  pull-requests: write  # This line gives the workflow pull request permissions

jobs:
  prettier:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.set_branch.outputs.branch_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Shorten SHA
        id: vars
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

       #Create and checkout to a new feature branch if there are changed files
      - name: Create feature branch
        id: set_branch
        run: |
          BRANCH_NAME="arunbagirthi/CLT-83255_automate_feature_branch_creation_prettier-${{ steps.vars.outputs.short_sha }}"
          git checkout -b $BRANCH_NAME
          echo "Created and checked out to branch $BRANCH_NAME"
          git branch -vv  # Debugging: Verify the branch tracking information
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      # Configure Git user for commits
      - name: Configure Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Initial commit
        run: |
          git commit --allow-empty -m "Initial commit for Prettier formatting"
          git push --set-upstream origin ${{ steps.set_branch.outputs.branch_name }}


      - name: Run Prettier
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: >-
            --write 
            "src/**/*.{js,ts,css,scss,html}"
            "brc/**/*.{js,ts,css,scss,html}"
            "prc/**/*.{js,ts,css,scss,html}"
          dry: false

      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

      - name: Fail Notice
        if: failure()
        run: echo "Prettier formatting failed, check the logs for details."
