name: Prettier PR

on:
  push:
    branches:
      - main

permissions:
  contents: write  # This line gives the workflow write permissions
  pull-requests: write  # This line gives the workflow pull request permissions

jobs:
  prettier:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: "feature/prettier-${{ github.sha }}"
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Collect changed files
      - name: Get changed files
        id: files
        run: |
          FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} -- 'src/' | grep -E '\.(js|ts|css|scss|html)$' || echo "")
          FILES_CLEANED=$(echo $FILES | xargs)  # Trims and converts newlines to spaces
          echo "FILES=$FILES_CLEANED" >> $GITHUB_ENV
          if [ -z "$FILES_CLEANED" ]; then
            echo "No files to format."
            echo "has_files=false" >> $GITHUB_OUTPUT
          else
            echo "Files to be formatted: $FILES_CLEANED"
            echo "has_files=true" >> $GITHUB_OUTPUT
          fi

      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

      # Create and checkout to a new feature branch if there are changed files
      - name: Create feature branch
        if: ${{ steps.files.outputs.has_files == 'true' }}
        run: |
          git checkout -b $BRANCH_NAME
          git push --set-upstream origin $BRANCH_NAME
          echo "Created and checked out to branch $BRANCH_NAME"
          git branch -vv  # Debugging: Verify the branch tracking information

      # Run Prettier to format code if there are changed files
      - name: Run Prettier
        if: ${{ steps.files.outputs.has_files == 'true' }}
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write ${{ env.FILES }}
          dry: false


      # Create a pull request if there are changed files
      - name: Create Pull Request
        if: ${{ steps.files.outputs.has_files == 'true' }}
        id: create_pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BRANCH_NAME }}
          base: main  # Ensure the base branch is main
          title: "Apply Prettier formatting"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
          body: "This PR applies Prettier formatting to the codebase."
          delete-branch: true

      # Notify failure if there are changed files
      - name: Fail Notice
        if: failure()
        run: echo "Prettier formatting failed, check the logs for details."
