name: Continuous Integration revised

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  prettier:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.files.outputs.files }}
      has_files: ${{ steps.files.outputs.has_files }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Get changed files
        id: files
        run: |
          FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} -- 'src/' | grep -E '\.(js|ts|css|scss|html)$' || echo "")
          echo "::set-output name=files::$FILES"
          if [ -z "$FILES" ]; then
            echo "Changed Files: None"
            echo "::set-output name=has_files::false"
          else
            echo "Changed Files: $FILES"
            echo "::set-output name=has_files::true"
          fi
        shell: bash

      - name: Debug output of FILES
        if: ${{ needs.prettier.outputs.has_files == 'true' }}
        run: echo "Files to be formatted:" ${{ needs.prettier.outputs.files }}

      - name: Run Prettier
        if: ${{ needs.prettier.outputs.has_files == 'true' }}
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write ${{ needs.prettier.outputs.files }}
          dry: false

      - name: Fail Notice
        if: failure()
        run: echo "Prettier formatting failed, check the logs for details."
